import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css' 
import Check from './check'
import Link from 'next/link'
import p1 from './photo.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  <h2>Statut en cours :</h2>
      <div className='flex'>
      <div className='flex0'>
        <Image
                        
                        src={p1}
                        alt="Picture of the author"
                        width={1400}
                        height={700}
                    />
      </div>
      
        <div className='flex1'>
          <h3>panier numéro : 564553434</h3>
          <p>Type d'action : Article scanné</p>

        </div>

        <div className='flex2'>
          <Link href="/check" ><a className='button'>Non frauduleux</a></Link>  
          
        </div>
      </div>
      

      
    </div>
  )
}
